name: Deploy latest to server
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            set -e

            mkdir -p $HOME/webapps
            git clone https://github.com/cs01/python-packaging-tools $HOME/webapps/python-packaging-tools || true
            cd $HOME/webapps/python-packaging-tools
            git fetch origin main
            git reset origin/main --hard

            # frontend
            cd $HOME/webapps/python-packaging-tools/frontend
            yarn
            yarn build

            # backend
            cd $HOME/webapps/python-packaging-tools/backend
            touch .env
            echo API_KEY=${{ secrets.API_KEY }} > .env

            # reload and restart systemd service
            sudo cp $HOME/webapps/python-packaging-tools/scripts/python-packaging-tools.service /etc/systemd/system/python-packaging-tools.service
            sudo systemctl daemon-reload
            sudo systemctl enable python-packaging-tools.service
            sudo systemctl restart python-packaging-tools